### ISSUE TITLE
MoveAnimation "In" animation does not work

### ISSUE THREAD

**Issue by alexpetin** [MPowerKit/Popups#3]
"Out" animation works correct, but "In" - not.

`    <popup:PopupPage.Animation>
        <anim:MoveAnimation />
    </popup:PopupPage.Animation>
`

**Comment by alexpetin** [comment]
https://github.com/microspaze/RGPopup.Maui/commit/6fdcd2e14d42e61830aaf4e31dbfd396a23bcd50

But Mopups MoveAnimation works without this :)

**Comment by Alex-Dobrynin** [comment]
fixed in 1.3.0. also it has a lot of other fixes
