### ISSUE TITLE
[iOS] Media picker (https://github.com/MPowerKit/MediaPlugin) is shown under current popup

### ISSUE THREAD

**Issue by amahera** [MPowerKit/Popups#4]
Steps:
1. Install https://github.com/MPowerKit/MediaPlugin
2. Open popup page
3. Call Media.Current.PickPhotoAsync()
4. Observe that the photo picker controller appears under the current popup page

Please notice that the same behavior was observed with MAUI FilePicker.PickAsync

**Comment by Alex-Dobrynin** [comment]
What OS? have you tried the latest one version of Popups?

**Comment by amahera** [comment]
@Alex-Dobrynin it's iOS 17.5, and it's in MPowerKit.Navigation.Popups so it should be v. 1.2.1.4

**Comment by amahera** [comment]
I didn't try Mopups yet but I will if it helps

**Comment by amahera** [comment]
I will let you know

**Comment by Alex-Dobrynin** [comment]
and one more thing. I suppose it will work the same in Mopups also, because on ios and mac, popups being opened as UIWindow, but mediaplugin uses ios and mac api to open picker which opens just new viewcontroller, which is obviously under the window and related to the main app window.

**Comment by amahera** [comment]
@Alex-Dobrynin with Mopups there is no such issue, here is repository to reproduce https://github.com/amahera/image-picker-reproduce-issue

**Comment by Alex-Dobrynin** [comment]
@amahera I've asked you, have you tried the latest version 1.3.0 or Popups, you said yes, but when i downloaded your repro project i've noticed that you are using v1.2.1.3 of Navigation.Popups, but the lates is 1.2.1.4 which is using latest Popups v1.3.0
I've updated the version on Navigation.Popups to the latest and issue is not reproducible anymore. Please be more attentive.

By the way. I've noticed appearing animation flickering using Mopups. But if you use my package it is very smooth
